# Defaults tasks for role debuginfod

- name: Configuring httpd
  import_role:
    name: httpd
  vars:
    httpd_tls: "{{ debuginfod_httpd_tls }}"
    httpd_html_autoindex_title: "CentOS Debuginfod service"

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ debuginfod_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
  when: debuginfod_httpd_tls

- name: Configuring httpd vhost
  template:
    src: 20_debuginfod_vhost.conf.j2
    dest: /etc/httpd/conf.d/20_debuginfod_vhost.conf
    mode: 0644
  notify:
    - restart_httpd

- name: Configuring https
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-debuginfod-vhost.conf
  when: debuginfod_httpd_tls  

- name: selinux | enabling booleans
  seboolean:
    name: "{{ item }}"
    state: True
    persistent: yes
  with_items:
    - httpd_can_network_connect

- name: Ensuring we have a document root for vhost
  file:
    path: "{{ debuginfod_httpd_dir }}"
    state: directory

- name: Dropping simple httpd index page
  template:
    src: index.html.j2
    dest: "{{ debuginfod_httpd_dir }}/index.html"
  tags:
    - httpd

- name: Ensuring some pkgs are installed for debuginfod
  yum:
    name: elfutils-debuginfod
    state: latest

- name: Configuring debuginfod service
  template:
    src: debuginfod.cfg.j2
    dest: /etc/sysconfig/debuginfod
  notify:
    - restart_debuginfod

- name: Ensuring debuginfod service is running
  service:
    name: debuginfod
    state: started
    enabled: True
