# Defaults tasks for role debuginfod

- name: Configuring httpd
  import_role:
    name: httpd
  vars:
    httpd_tls: "{{ debuginfod_httpd_tls }}"
    httpd_html_autoindex_title: "CentOS Debuginfod service"

- import_role:
    name: httpd
    tasks_from: pki-tls
  vars:
    pki_hostname: "{{ debuginfod_httpd_hostname }}"
  notify:
    - restart_httpd
  tags:
    - tls
  when: debuginfod_httpd_tls

- name: Configuring httpd vhost
  template:
    src: 20_debuginfod_vhost.conf.j2
    dest: /etc/httpd/conf.d/20_debuginfod_vhost.conf
    mode: 0644
  notify:
    - restart_httpd

- name: Configuring https
  template:
    src: "{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: 0644
  notify:
    - restart_httpd
  with_items:
    - ssl-debuginfod-vhost.conf
  when: debuginfod_httpd_tls  
   
- name: Ensuring we have a document root for vhost
  file:
    path: "{{ debuginfod_httpd_dir }}"
    state: directory


